slam_toolbox:
  ros__parameters:
    use_sim_time: false
    publish_tf_map: true
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: scan
    mode: mapping
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.5
    transform_timeout: 0.1
    map_update_interval: 1.0
    use_scan_matching: true
    enable_interactive_mode: false

